# -----------------------------------------------------------
# Project Configuration Notes:
#
# - Second volume mounts project data separately to avoid conflict with SQL data volume.
#   Make sure your project data is stored on the host at /var/opt/mssql/dwh_project
#   for proper mounting and to enable BULK INSERT access from the SQL Server container.
#
# - Environment variables like SA_PASSWORD are stored in a separate .env file
#   for better security and easier configuration management.
#
# - Place the .env file in the root directory of your project (same level as docker-compose.yml).
#   Example:
#     /your-project/
#     ├── docker-compose.yml
#     └── .env
#
# - If you're using Git, add `.env` to your `.gitignore` file to avoid committing sensitive data.
# -----------------------------------------------------------

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: ${SQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - /var/opt/mssql/dwh_project:/var/opt/mssql/dwh_project:ro  
    restart: always

volumes:
  sql_data:
